sudo: false
dist: trusty
language: node_js
node_js:
- "8.11.2"

env:
  global:
    - PATH=$HOME/.local/bin:$PATH

branches:
  only:
  - master

addons:
  apt:
    packages:
    - optipng

cache:
  timeout: 2592000  # 1 week
  directories:
    - "external"
    - "src/images/ships"
    - "node_modules"
    - $HOME/.local

before_install:
  - pip install --user awscli

install:
 - yarn install
 - yarn versionCheck
 - yarn WCTF
 - yarn KC3Avatars
 - yarn sprites

before_script: yarn lint

script: yarn build

deploy:
  skip_cleanup: true
  script: bash scripts/deploy.sh
  on:
    branch: master