sudo: false
dist: trusty
language: node_js
node_js:
- "8.11.2"

env:
  global:
    - PATH=$HOME/.local/bin:$PATH

addons:
  apt:
    packages:
    - optipng

cache:
  directories:
    - "node_modules"
    - $HOME/.local

before_install:
  - pip install --local aws-cli

install:
 - yarn install
 - yarn WCTF
 - yarn KC3Avatars
 - yarn sprites

before_script: yarn lint

script: yarn build

after_success:
  - find dist -name "*.png" -exec optipng {} \;
  - aws s3 sync ./dist/ s3://${AWS_CF_DOMAIN} --acl public-read --metadata-directive REPLACE --cache-control public,max-age=5184000 --exclude "index.html" --delete
  - aws s3 cp ./dist/index.html s3://${AWS_CF_DOMAIN}/index.html --acl public-read --metadata-directive REPLACE --cache-control public,max-age=3600
  - aws cloudfront create-invalidation --distribution-id=${AWS_CF_DISTRIBUTION_ID} --paths /index.html