sudo: false
dist: trusty
language: node_js
node_js:
- "8.11.2"

cache:
  directories:
    - "node_modules"

before_install: true

install:
 - yarn install
 - yarn WCTF
 - yarn KC3Avatars
 - yarn sprites

before_script: yarn lint

script: yarn build

deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  #keep-history: true
  on:
    branch: master