sudo: false
dist: trusty
language: node_js
node_js:
- "12.9.1"

env:
  global:
    - PATH=$HOME/.local/bin:$PATH

branches:
  only:
  - master
  - dev

addons:
  apt:
    packages:
    - optipng

cache:
  timeout: 2592000  # 1 month
  directories:
    - "external"
    - "src/images/raw_ships"
    - "src/images/ships"
    - "src/images/item_types"
    - "node_modules"
    - $HOME/.local

before_install:
  - pip install --user awscli

install:
 - npm install
 - npm run versionCheck
 - npm run WCTF
 - npm run KC3Avatars
 - npm run KC3Items
 - npm run sprites

before_script: npm run lint

script: npm run build

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh production
    on:
      branch: master
    #
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh dev
    on:
      branch: dev
