name: deploy master branch to s3
on:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules, WCTF and images
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            ~/.npm
            external
            src/images/raw_ships
            src/images/ships
            src/images/item_types
            $HOME/.local
            node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm install

      - name: Install awscli
        run: pip install --user awscli

      - name: install optipng
        run: sudo apt-get update && sudo apt-get install optipng

      - name: Linter
        run: npm run lint

      - name: Cache version check
        run: npm run versionCheck

      - name: WCTF update
        run: npm run WCTF

      - name: KC3Avatars update
        run: npm run KC3Avatars

      - name: KC3Items update
        run: npm run KC3Items

      - name: Build Sprites
        run: npm run sprites

      - name: Build JS
        run: npm run build

      - name: Deploy to aws
        run: bash scripts/deploy.sh production
